import {
  Activity,
  Baby,
  Beef,
  Bone,
  Brain,
  ChefHat,
  Coffee,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Eye,
  Filter,
  Fish,
  Flame,
  FlaskConical,
  Flower2,
  Gauge,
  Heart,
  HeartPulse,
  Leaf,
  type LucideIcon,
  Mars,
  Moon,
  Package,
  PersonStanding,
  Pill,
  Salad,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smile,
  Sparkles,
  Stethoscope,
  Sun,
  TrendingDown,
  UtensilsCrossed,
  Venus,
  Waves,
  Wind,
  Zap,
} from "lucide-react";

export const CATEGORY_ICONS: { name: string; label: string; icon: LucideIcon }[] = [
  { name: "Eye", label: "Na wzrok", icon: Eye },
  { name: "Heart", label: "Serce", icon: Heart },
  { name: "HeartPulse", label: "Krążenie i libido", icon: HeartPulse },
  { name: "Brain", label: "Mózg i pamięć", icon: Brain },
  { name: "Bone", label: "Kości i stawy", icon: Bone },
  { name: "Shield", label: "Odporność", icon: Shield },
  { name: "ShieldAlert", label: "Alergie", icon: ShieldAlert },
  { name: "ShieldCheck", label: "Antyoksydanty", icon: ShieldCheck },
  { name: "Moon", label: "Sen", icon: Moon },
  { name: "Zap", label: "Energia", icon: Zap },
  { name: "Sun", label: "Witamina D", icon: Sun },
  { name: "Salad", label: "Trawienie i jelita", icon: Salad },
  { name: "Dumbbell", label: "Sport", icon: Dumbbell },
  { name: "Baby", label: "Ciąża i płodność", icon: Baby },
  { name: "Pill", label: "Suplementy i witaminy", icon: Pill },
  { name: "Sparkles", label: "Uroda i skóra", icon: Sparkles },
  { name: "Flame", label: "Metabolizm i spalanie", icon: Flame },
  { name: "Flower2", label: "Zdrowie kobiet", icon: Flower2 },
  { name: "Stethoscope", label: "Zdrowie ogólne", icon: Stethoscope },
  { name: "Droplet", label: "Nawodnienie i układ moczowy", icon: Droplet },
  { name: "Droplets", label: "Detoks", icon: Droplets },
  { name: "Wind", label: "Układ oddechowy", icon: Wind },
  { name: "Filter", label: "Wątroba", icon: Filter },
  { name: "Gauge", label: "Tarczyca i metabolizm", icon: Gauge },
  { name: "TrendingDown", label: "Obniżanie cukru/cholesterolu", icon: TrendingDown },
  { name: "Fish", label: "Ryby i omega-3", icon: Fish },
  { name: "Beef", label: "Mięso", icon: Beef },
  { name: "Coffee", label: "Kawa i desery", icon: Coffee },
  { name: "ChefHat", label: "Akcesoria kuchenne", icon: ChefHat },
  { name: "FlaskConical", label: "Olejki eteryczne", icon: FlaskConical },
  { name: "Venus", label: "Dla kobiet", icon: Venus },
  { name: "Mars", label: "Dla mężczyzn", icon: Mars },
  { name: "Smile", label: "Nastrój", icon: Smile },
  { name: "Waves", label: "Układ limfatyczny", icon: Waves },
  { name: "Package", label: "Produkty ogólne", icon: Package },
  { name: "UtensilsCrossed", label: "Apetyt", icon: UtensilsCrossed },
  { name: "Activity", label: "Aminokwasy i kondycja", icon: Activity },
  { name: "Ear", label: "Na słuch", icon: Ear },
  { name: "Leaf", label: "Naturalne i adaptogeny", icon: Leaf },
  { name: "PersonStanding", label: "Senior", icon: PersonStanding },
];

export function getCategoryIcon(name?: string | null): LucideIcon | null {
  if (!name) return null;
  return CATEGORY_ICONS.find((i) => i.name === name)?.icon ?? null;
}
